sudo: required
language: node_js
node_js:
  - "14"

addons:
  apt:
    packages:
      - libgconf-2-4

services:
  - docker

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
    - npm run cy:info

before_install:
  - docker build -t pavantekal/docker_test .
  - docker run -d -p 127.0.0.1:80:4567 pavantekal/docker_test
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pavantekal/docker_test
  - eval $(aws ecr get-login --region us-east-1)
  - docker tag pavantekal/docker_test 786556925446.dkr.ecr.us-east-1.amazonaws.com/my-web-app
  - docker push 786556925446.dkr.ecr.us-east-1.amazonaws.com/my-web-app

after_success:

script:
  - npm install
  - echo $pwd
  # - npm run start:ci &
  # - npm run cy:run -- --record --parallel --group $STAGE_NAME
  - npm run cy:run -- --spec "cypress/integration/examples/simpletest.spec.js"
